locals {
  custom_css = <<-CSS
    @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;600&display=swap');

    :root {
      --green: #00ff41;
      --amber: #ffb000;
      --bg: #0a0a0a;
      --fg: #e0e0e0;
      --code-bg: #1a1a2e;
    }

    body, .reveal {
      background-color: var(--bg);
      font-family: 'Fira Code', 'Courier New', monospace;
      text-transform: lowercase;
    }

    .reveal h1, .reveal h2, .reveal h3 {
      color: var(--green);
      font-family: 'Fira Code', 'Courier New', monospace;
      text-transform: none;
      font-weight: 600;
      letter-spacing: -0.02em;
    }

    .reveal h1 { font-size: 1.8em; }
    .reveal h2 { font-size: 1.4em; }
    .reveal h3 { font-size: 1.1em; }

    .reveal p, .reveal li, .reveal td {
      color: var(--fg);
      text-align: left;
      font-size: 0.7em;
      line-height: 1.6;
    }

    .reveal ul, .reveal ol {
      display: block;
      margin-left: 1em;
    }

    .reveal .amber { color: var(--amber); }
    .reveal .green { color: var(--green); }
    .reveal .dim { color: #666; }

    .reveal pre {
      width: 95%;
      margin: 0.5em auto;
    }

    .reveal pre code {
      font-size: 0.55em;
      line-height: 1.5;
      background: var(--code-bg);
      border: 1px solid var(--green);
      border-radius: 4px;
      padding: 0.8em;
      max-height: 500px;
      text-transform: none;
    }

    .reveal code:not(pre code) {
      color: var(--amber);
      font-size: 0.9em;
      background: rgba(255, 176, 0, 0.1);
      padding: 0.1em 0.3em;
      border-radius: 3px;
      text-transform: none;
    }

    .reveal .slide-number {
      color: var(--green);
      font-family: 'Fira Code', monospace;
      font-size: 0.5em;
    }

    .tf-plan {
      font-family: 'Fira Code', monospace;
      text-align: left;
      font-size: 0.65em;
      line-height: 1.8;
    }

    .tf-plan .resource { color: var(--green); }
    .tf-plan .comment { color: #666; }

    .reveal .prompt::before {
      content: '$ ';
      color: var(--amber);
    }

    .reveal blockquote {
      border-left: 4px solid var(--amber);
      background: rgba(255, 176, 0, 0.05);
      padding: 0.5em 1em;
      width: 85%;
    }

    .reveal table {
      margin: 0.5em auto;
      border-collapse: collapse;
    }

    .reveal table th {
      color: var(--green);
      border-bottom: 2px solid var(--green);
      padding: 0.4em 0.8em;
      font-size: 0.65em;
    }

    .reveal table td {
      border-bottom: 1px solid #333;
      padding: 0.4em 0.8em;
      font-size: 0.6em;
    }

    .reveal .section-header {
      border-bottom: 2px solid var(--green);
      padding-bottom: 0.3em;
      margin-bottom: 0.5em;
    }
  CSS

  slides = <<-HTML

    <!-- ============================================ -->
    <!-- SLIDE 1: terraform init — Title              -->
    <!-- ============================================ -->
    <section>
      <p style="color: var(--amber); font-size: 0.7em; margin-bottom: 0;">$ terragrunt init</p>
      <p style="color: #666; font-size: 0.55em;">Initializing provider plugins...</p>
      <p style="color: var(--green); font-size: 0.55em;">Terraform has been successfully initialized!</p>
      <br>
      <h1>${var.talk_title}</h1>
      <p style="color: var(--green); font-size: 0.8em; text-align: center;">${var.presenter_name}</p>
      <aside class="notes">
        open with the meta-joke: this presentation was generated by running terragrunt apply. every slide is a resource attribute inside a terraform locals block, and the whole project uses the same terragrunt patterns we'll be discussing today. the source is on github if anyone wants to look at it afterwards. keep this brief — it's a fun opener but don't dwell on it. transition into the agenda.
      </aside>
    </section>

    <!-- ============================================ -->
    <!-- SLIDE 2: terraform plan — Table of Contents  -->
    <!-- ============================================ -->
    <section>
      <h2 class="prompt">terragrunt plan</h2>
      <div class="tf-plan">
        <p class="comment"># Terraform will perform the following actions:</p>
        <br>
        <p class="resource">+ slide.history_of_terraform</p>
        <p class="resource">+ slide.what_terraform_does</p>
        <p class="resource">+ slide.core_concepts</p>
        <p class="resource">+ slide.writing_terraform</p>
        <p class="resource">+ slide.terragrunt</p>
        <p class="resource">+ slide.cicd_at_tabs</p>
        <br>
        <p>Plan: <span class="amber">6 slides</span> to add, <span class="amber">0</span> to change, <span class="amber">0</span> to destroy.</p>
      </div>
      <aside class="notes">
        walk through the agenda briefly. the framing device is the terragrunt lifecycle — init, plan, apply, destroy — with the main content in the "apply" phase. six content sections: history for context, what terraform does, core concepts as a shared vocabulary refresher, a practical hcl example, terragrunt (the most important section for our team), and finally how it all wires into our ci/cd at tabs. mention that questions are welcome throughout, not just at the end.
      </aside>
    </section>

    <!-- ============================================ -->
    <!-- terraform apply — Main Content Begins        -->
    <!-- ============================================ -->

    <!-- SLIDE 3: History of Terraform -->
    <section>
      <section>
        <h2 class="section-header">where terraform came from</h2>
        <p style="color: var(--green); font-size: 0.6em;">slide.history_of_terraform: Creating...</p>
        <aside class="notes">this section provides context for terraform's design philosophy and the recent license controversy. it helps explain why terraform works the way it does and where the ecosystem stands today. keep it moving — three sub-slides, don't spend more than a couple minutes here.</aside>
      </section>

      <section>
        <h3>hashicorp, 2012</h3>
        <ul>
          <li><span class="amber">2012</span> — Mitchell Hashimoto and Armon Dadgar start HashiCorp</li>
          <li>Vagrant was the first product — codifying dev environments</li>
          <li>Then Consul, Vault, Nomad, Packer — all infrastructure tooling</li>
        </ul>
        <aside class="notes">hashicorp was founded in 2012 by mitchell hashimoto and armon dadgar. mitchell was already well-known in the devops community for vagrant, which let developers define reproducible development environments in code. the founding thesis of hashicorp was that this same idea — codifying infrastructure — could be applied across the entire stack: service discovery (consul), secrets management (vault), scheduling (nomad), image building (packer), and of course provisioning (terraform). all of these tools share a common philosophy around declarative configuration and the separation of intent from execution.</aside>
      </section>

      <section>
        <h3>terraform 0.1, july 2014</h3>
        <ul>
          <li><span class="amber">July 2014</span> — Terraform 0.1, open source under MPL 2.0</li>
          <li>Big idea: one tool that works across cloud providers</li>
          <li>Plan → apply workflow was there from the start</li>
          <li><span class="amber">HCL</span> replaced JSON configs — human-readable but still machine-parseable</li>
        </ul>
        <aside class="notes">terraform launched in july 2014 as version 0.1 under the mozilla public license 2.0, which is a permissive open-source license. the key differentiator from the start was provider-agnosticism — at the time, aws cloudformation was the main iac tool, but it only worked with aws. terraform's bet was that teams would want a single workflow regardless of which cloud provider (or combination of providers) they were using. the plan-then-apply workflow was a core design decision from day one: you always preview changes before they execute. hcl was introduced as an alternative to writing raw json configurations — it was designed to be readable by humans while still being unambiguous enough for machines to parse. yaml was not chosen because of its well-known issues with implicit type coercion and whitespace sensitivity.</aside>
      </section>

      <section>
        <h3>the bsl relicense, 2023</h3>
        <ul>
          <li><span class="amber">August 2023</span> — HashiCorp relicenses Terraform from MPL 2.0 to BSL 1.1</li>
          <li>BSL restricts competing commercial use — most production use is fine</li>
          <li><span class="amber">September 2023</span> — Linux Foundation announces <span class="green">OpenTofu</span>, a community fork keeping MPL 2.0</li>
          <li>For us, nothing changed — BSL doesn't affect how we use it</li>
        </ul>
        <aside class="notes">in august 2023, hashicorp changed terraform's license from mpl 2.0 to the business source license (bsl) 1.1. the bsl prohibits using terraform to build competing commercial products — so companies like spacelift or env0 were affected — but standard production use by end-user companies is explicitly permitted. the community response was swift: within a month, the linux foundation announced opentofu, a fork that maintains the mpl 2.0 license. opentofu aims for drop-in compatibility with terraform. for our purposes at tabs, the license change has zero practical impact — we're end users, not building a competing terraform-as-a-service product. we stayed on hashicorp terraform. if someone asks about opentofu: it's a valid option and a good insurance policy, but the ecosystem (providers, modules, documentation) is still overwhelmingly oriented around terraform proper.</aside>
      </section>
    </section>

    <!-- SLIDE 4: What Terraform Is -->
    <section>
      <section>
        <h2 class="section-header">what terraform does</h2>
        <p style="color: var(--green); font-size: 0.6em;">slide.what_terraform_does: Creating...</p>
        <aside class="notes">this section explains what terraform actually is and how it works at a high level. the audience has some exposure, so this is about establishing shared understanding — not convincing anyone to use it. we already use it. two sub-slides: the iac model, then the workflow.</aside>
      </section>

      <section>
        <h3>infrastructure as code</h3>
        <ul>
          <li><span class="amber">Declarative</span> — you describe what you want, not how to get there</li>
          <li><span class="amber">Idempotent</span> — run it twice, same result</li>
          <li><span class="amber">Version-controlled</span> — infra changes go through PRs like any other code</li>
          <li>Your .tf files <em>are</em> the docs for what's deployed</li>
        </ul>
        <aside class="notes">terraform is an infrastructure-as-code tool. you write configuration files that describe the infrastructure you want, and terraform figures out how to create, update, or delete resources to match. declarative means you specify the end state, not the steps — terraform handles the ordering and api calls. idempotency means running the same config twice produces the same result, which makes it safe to re-run. because everything is in .tf files checked into git, infrastructure changes go through the same pull request and review process as application code. the config files themselves serve as living documentation of what's actually deployed.</aside>
      </section>

      <section>
        <h3>the workflow: init, plan, apply</h3>
        <ul>
          <li><code>terraform init</code> — downloads providers and sets up the backend</li>
          <li><code>terraform plan</code> — compares your config to current state, shows what would change</li>
          <li><code>terraform apply</code> — executes the changes</li>
          <li>3,000+ providers — AWS, GCP, Datadog, GitHub, anything with an API</li>
          <li>HCL — a configuration language designed for infrastructure</li>
        </ul>
        <aside class="notes">the core workflow is three commands. init downloads the provider plugins and configures the backend (where state is stored). plan reads your config, compares it to the current state, and produces a diff showing exactly what will be created, modified, or destroyed — nothing happens yet. apply executes the plan. this preview-before-execute model is one of terraform's most important properties: you always know what's going to happen before it happens. terraform talks to external services through providers — there are over 3,000 of them covering cloud providers, saas tools, dns services, monitoring platforms, and more. the configuration language is hcl (hashicorp configuration language), which was purpose-built for infrastructure definitions — more readable than json, less ambiguous than yaml.</aside>
      </section>
    </section>

    <!-- SLIDE 5: Core Concepts -->
    <section>
      <section>
        <h2 class="section-header">the building blocks</h2>
        <p style="color: var(--green); font-size: 0.6em;">slide.core_concepts: Creating...</p>
        <aside class="notes">this is a refresher, not an introduction. the goal is to establish a shared vocabulary so the terragrunt and ci/cd sections make sense to everyone. six concepts: providers, resources, variables and outputs, state, and modules. spend roughly one minute per sub-slide. if the audience seems comfortable, move through this quickly — the terragrunt section is where the new information lives for most people.</aside>
      </section>

      <section>
        <h3>providers</h3>
        <p>Plugins that let Terraform talk to APIs.</p>
        <pre><code class="language-hcl">provider "aws" {
  region = "us-east-1"
}

provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}</code></pre>
        <ul>
          <li>Separate binaries, pulled in during <code>terraform init</code></li>
          <li>Version-pinned in <code>required_providers</code></li>
          <li>You can mix providers — AWS for infra, Datadog for monitoring, same config</li>
        </ul>
        <aside class="notes">providers are plugins — separate go binaries — that terraform downloads during the init phase. each provider teaches terraform how to interact with a specific api. the aws provider is the most widely used and has hundreds of resource types covering everything from ec2 instances to iam policies to cloudwatch alarms. we use the aws provider for all our infrastructure, the datadog provider for monitoring configuration, and the github provider for repository settings. you can use multiple providers in the same configuration, which means a single terraform apply can provision an aws resource, set up its monitoring in datadog, and configure the github repo that deploys to it. providers are version-pinned in the required_providers block to prevent unexpected breaking changes.</aside>
      </section>

      <section>
        <h3>resources</h3>
        <p>Each resource maps to a real thing in your cloud account.</p>
        <pre><code class="language-hcl">resource "aws_s3_bucket" "logs" {
  bucket = "my-app-logs-bucket"

  tags = {
    Environment = "production"
  }
}</code></pre>
        <ul>
          <li><code>resource "TYPE" "NAME" { ... }</code> — type prefix tells you the provider</li>
          <li>Tracked in state by address: <code>aws_s3_bucket.logs</code></li>
        </ul>
        <aside class="notes">resources are the core building block. each resource declaration maps to exactly one real infrastructure object — an s3 bucket, an ec2 instance, a security group. the format is always resource "type" "name", where the type prefix indicates the provider (aws_, google_, azurerm_). terraform tracks each resource in its state file by address, like aws_s3_bucket.logs. an important subtlety: if you rename a resource in your config, terraform interprets that as "destroy the old resource and create a new one" — not as a rename. you can use moved blocks to handle this without destruction, but it's a common gotcha for newcomers. the name is local to your terraform configuration; the actual cloud object has its own identifier (an arn, an instance id, etc.).</aside>
      </section>

      <section>
        <h3>variables, outputs, locals</h3>
        <pre><code class="language-hcl">variable "environment" {
  type        = string
  description = "Deployment environment"
  default     = "dev"
}

output "bucket_arn" {
  description = "ARN of the logs bucket"
  value       = aws_s3_bucket.logs.arn
}</code></pre>
        <ul>
          <li><span class="amber">Variables</span> — inputs. Set via <code>-var</code>, <code>.tfvars</code> files, or env vars</li>
          <li><span class="amber">Outputs</span> — values exported after apply, used by other modules or CI</li>
          <li><span class="amber">Locals</span> — internal computed values (think private variables)</li>
        </ul>
        <aside class="notes">a useful mental model is to think of a terraform module like a function. variables are the parameters — they define the public interface and can be set via command-line flags (-var), .tfvars files, or environment variables (TF_VAR_ prefix). outputs are the return values — they're computed after apply and can be consumed by other modules or read by ci scripts. locals are private helper values for intermediate computations within the module. the distinction between these three becomes very important when you start composing modules: variables define what a module needs from its caller, outputs define what a module provides to the world, and locals are implementation details that callers never see.</aside>
      </section>

      <section>
        <h3>state</h3>
        <ul>
          <li>Terraform keeps a <span class="amber">state file</span> mapping your config to real resources</li>
          <li>Locally it's just <code>terraform.tfstate</code> — for teams, use a remote backend (S3 + DynamoDB)</li>
          <li>Contains sensitive data. Treat it like a secret.</li>
          <li>Locking prevents two people from applying at the same time</li>
        </ul>
        <pre><code class="language-hcl">terraform {
  backend "s3" {
    bucket         = "my-terraform-state"
    key            = "prod/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}</code></pre>
        <aside class="notes">state is the most operationally important concept in terraform. the state file is a json document that records the mapping between every resource in your configuration and the corresponding real-world infrastructure object. without it, terraform has no way of knowing what exists. if you lose the state, you have to manually import every resource one by one — which is painful and error-prone. for individual use, a local terraform.tfstate file works fine. for teams, a remote backend is non-negotiable. we use s3 for storage and dynamodb for state locking, which prevents two engineers (or two ci jobs) from running terraform apply simultaneously and corrupting the state. the state file also contains sensitive data — resource attributes, connection strings, sometimes passwords — so it should be encrypted at rest and access-controlled. terragrunt manages our backend configuration automatically, which we'll cover in the terragrunt section.</aside>
      </section>

      <section>
        <h3>modules</h3>
        <ul>
          <li>Just a directory of <code>.tf</code> files — that's it</li>
          <li>Called with a <code>module</code> block, passing variables as arguments</li>
        </ul>
        <pre><code class="language-hcl">module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.1.0"

  name = "my-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-east-1a", "us-east-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]
}</code></pre>
        <ul>
          <li>Public registry has thousands (VPC, ECS, RDS, etc.)</li>
          <li>We also write internal modules that bake in our conventions</li>
        </ul>
        <aside class="notes">a module is simply a directory containing .tf files. the root of your project is itself a module (the "root module"). you call other modules using a module block, passing variables as arguments. the public terraform registry has thousands of community-maintained modules for common patterns — vpcs, ecs clusters, rds instances. we use some of these, but we also maintain an internal terraform-modules repository that encodes our company's specific opinions: tagging standards, security group defaults, naming conventions, monitoring integration. our internal modules are organized in a three-tier hierarchy: 1-core (foundational utilities like tagging and labeling), 2-component (reusable building blocks like alb and ecr), and 3-service (complete solutions that compose core and component modules). this tiering enforces a dependency direction — service modules can depend on components, but components cannot depend on services.</aside>
      </section>
    </section>

    <!-- SLIDE 6: Writing Terraform -->
    <section>
      <section>
        <h2 class="section-header">real hcl</h2>
        <p style="color: var(--green); font-size: 0.6em;">slide.writing_terraform: Creating...</p>
        <aside class="notes">transition from concepts to practice. this section shows a realistic terraform example using aws — not a hello-world, but the kind of code you'd actually encounter in a production codebase. two sub-slides: one showing the variables and locals setup, one showing the resource and outputs. walk through the code on screen and point out the patterns.</aside>
      </section>

      <section>
        <h3>ec2 instance — variables and locals</h3>
        <pre><code class="language-hcl">locals {
  environment = "production"
  app_name    = "api-server"

  common_tags = {
    ManagedBy   = "terraform"
    Environment = local.environment
    Application = local.app_name
  }
}

variable "instance_type" {
  type        = string
  default     = "t3.micro"
  description = "EC2 instance type"
}

variable "ami_id" {
  type        = string
  description = "AMI ID for the instance"
}</code></pre>
        <aside class="notes">walk through this code top to bottom. the locals block defines values that are computed or shared across multiple resources — here, the environment name, application name, and a common_tags map. the common_tags pattern is ubiquitous in production terraform: you define a set of tags once and apply them to every resource. this ensures consistent metadata for cost allocation, ownership tracking, and operations. the variables block defines values that change between deployments — instance_type has a sensible default, ami_id is required (no default). the distinction matters: locals are internal implementation details, variables are the public interface.</aside>
      </section>

      <section>
        <h3>ec2 instance — resource and outputs</h3>
        <pre><code class="language-hcl">resource "aws_instance" "app" {
  ami           = var.ami_id
  instance_type = var.instance_type
  subnet_id     = module.vpc.private_subnets[0]

  tags = merge(local.common_tags, {
    Name = "$${local.app_name}-$${local.environment}"
  })

  lifecycle {
    create_before_destroy = true
  }
}

output "instance_id" {
  description = "ID of the EC2 instance"
  value       = aws_instance.app.id
}

output "private_ip" {
  description = "Private IP address"
  value       = aws_instance.app.private_ip
}</code></pre>
        <aside class="notes">several patterns to point out here. first, module.vpc.private_subnets[0] — this references an output from a vpc module defined elsewhere, which is how modules compose in terraform. the resource doesn't need to know how the vpc was created, just that it exposes a list of private subnet ids. second, the merge() function combines the common_tags map with resource-specific tags, so this instance gets all the standard tags plus its own name tag. third, the lifecycle block with create_before_destroy — this tells terraform to create the replacement instance before destroying the old one during updates, which is a standard pattern for minimizing downtime. finally, the outputs export the instance id and private ip, which other modules or ci scripts can consume. in our actual codebase, these outputs feed into things like dns records, load balancer target groups, and monitoring dashboards.</aside>
      </section>
    </section>

    <!-- SLIDE 7: Terragrunt -->
    <section>
      <section>
        <h2 class="section-header">terragrunt</h2>
        <p style="color: var(--green); font-size: 0.6em;">slide.terragrunt: Creating...</p>
        <aside class="notes">terragrunt is a thin wrapper around terraform, built by gruntwork. it doesn't replace terraform — it runs terraform under the hood. its purpose is to solve the configuration management problems that emerge when you scale terraform across multiple environments and services. if anyone in the audience hasn't used terragrunt before, that's completely fine — this section will cover what it does and why we adopted it. as a meta-note: this very presentation is managed by terragrunt. the terraform module lives in modules/presentation/ and a terragrunt.hcl wrapper in live/presentation/ provides the inputs and inherits the root configuration. it's a small but real example of the patterns we're about to discuss.</aside>
      </section>

      <section>
        <h3>what breaks at scale</h3>
        <ul>
          <li>Vanilla Terraform gets <span class="amber">repetitive</span> fast</li>
          <li>Same backend config, same provider block, copy-pasted across dozens of directories</li>
          <li>No built-in way to express <span class="amber">dependencies between stacks</span></li>
          <li>Environment promotion means duplicating configs by hand</li>
        </ul>
        <p style="color: var(--green); font-size: 0.65em;">Terragrunt's whole thing: keep your Terraform DRY.</p>
        <aside class="notes">the core problem is duplication. when you have multiple services (auth, api, events, etc.) each deployed across multiple environments (dev, prod), you end up with dozens of directories that each need nearly identical backend configurations, provider blocks, and variable patterns. at our scale — roughly 10+ services across 2 environments — that means 20+ copies of the same boilerplate. maintaining consistency across all of them is tedious and error-prone. terraform also has no built-in mechanism for expressing dependencies between separate state files (stacks), so if your ecs service depends on a vpc, you have to manually ensure the vpc is applied first. terragrunt addresses all of these problems through configuration inheritance, code generation, and a dependency graph system.</aside>
      </section>

      <section>
        <h3>root config inheritance</h3>
        <p>One root config, thin overrides everywhere else.</p>
        <pre><code class="language-hcl"># root terragrunt.hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket         = "my-company-terraform-state"
    key            = "$${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-locks"
  }
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = &lt;&lt;EOF
provider "aws" {
  region = "us-east-1"
}
EOF
}</code></pre>
        <aside class="notes">this is the root terragrunt configuration that all child modules inherit. the remote_state block defines the s3 backend configuration once, and the key uses path_relative_to_include() — a terragrunt function that automatically namespaces state files based on directory path. so dev/vpc gets its state at dev/vpc/terraform.tfstate and prod/ecs gets prod/ecs/terraform.tfstate, all without any manual configuration per module. the generate blocks are terragrunt's code generation feature: before terraform runs, terragrunt writes a backend.tf and provider.tf into the working directory with the correct values. terraform never sees terragrunt at all — it just sees normal .tf files. this is a key architectural decision: terragrunt is not a terraform replacement, it's a preprocessor. anything terraform can do, you can still do; terragrunt just automates the repetitive parts.</aside>
      </section>

      <section>
        <h3>environment layout</h3>
        <pre><code class="language-bash">sre/
├── terragrunt.hcl              # root config
├── dev/
│   ├── account.terragrunt.hcl  # AWS account ID + profile
│   └── us-east-1/
│       ├── region.terragrunt.hcl
│       └── dev/
│           ├── environment.terragrunt.hcl
│           ├── vpc/terragrunt.hcl
│           ├── ecs/terragrunt.hcl
│           └── rds-backend-cluster/terragrunt.hcl
└── prod/
    ├── account.terragrunt.hcl  # different AWS account
    └── us-east-1/
        └── prod/
            ├── vpc/terragrunt.hcl
            ├── ecs/terragrunt.hcl
            └── rds-backend-cluster/terragrunt.hcl</code></pre>
        <p>Each leaf <code>terragrunt.hcl</code> is minimal:</p>
        <pre><code class="language-hcl">include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../modules//vpc"
}

inputs = {
  environment = "dev"
  cidr_block  = "10.0.0.0/16"
}</code></pre>
        <aside class="notes">this slide shows our actual directory structure at tabs (simplified). the key insight is that the directory hierarchy itself encodes the environment model: account, region, environment, then component. each layer has its own .hcl file that sets contextual values — account.terragrunt.hcl sets the aws account id and profile, region.terragrunt.hcl sets the aws region, environment.terragrunt.hcl sets the environment name. these all get composed through terragrunt's include mechanism. dev and prod live in entirely separate aws accounts for isolation, which is an aws best practice for blast-radius reduction. promoting a change from dev to prod means pointing at the same terraform module source with different input values and a different aws account — the root config, provider setup, and backend config are all inherited and don't need to be duplicated. the leaf terragrunt.hcl files are intentionally minimal: just an include, a source, and inputs.</aside>
      </section>

      <section>
        <h3>generated backends</h3>
        <ul>
          <li>Terragrunt <span class="green">generates</span> the S3 backend config from the <code>remote_state</code> block</li>
          <li>State key = directory path, automatically</li>
          <li>Creates the S3 bucket and DynamoDB table if they don't exist yet</li>
          <li>No more copy-pasting backend blocks</li>
        </ul>
        <pre><code class="language-bash"># Without Terragrunt: manual backend in every module
# With Terragrunt: one remote_state block in root, inherited everywhere

# State paths generated automatically:
# dev/vpc/     → s3://bucket/dev/vpc/terraform.tfstate
# prod/ecs/    → s3://bucket/prod/ecs/terraform.tfstate</code></pre>
        <aside class="notes">this is one of the biggest quality-of-life improvements terragrunt provides. in vanilla terraform, backend configuration blocks cannot use variables or expressions — it's one of the most frustrating limitations of the language, and it exists because the backend needs to be resolved before terraform can evaluate any other configuration. this means every module needs a hardcoded backend block with the bucket name, state key, region, and dynamodb table. terragrunt sidesteps this limitation entirely by generating the backend.tf file with the correct values before terraform ever runs. the state key is derived from the directory path automatically, so dev/vpc and prod/ecs each get their own isolated state file without any manual configuration. terragrunt will also create the s3 bucket and dynamodb lock table if they don't already exist, which simplifies bootstrapping new environments.</aside>
      </section>

      <section>
        <h3>cross-stack dependencies</h3>
        <pre><code class="language-hcl"># ecs/terragrunt.hcl
dependency "vpc" {
  config_path = "../vpc"

  mock_outputs = {
    vpc_id             = "vpc-mock-12345"
    private_subnet_ids = ["subnet-mock-1", "subnet-mock-2"]
  }
  mock_outputs_allowed_terraform_commands = ["plan", "validate"]
}

inputs = {
  vpc_id     = dependency.vpc.outputs.vpc_id
  subnet_ids = dependency.vpc.outputs.private_subnet_ids
}</code></pre>
        <ul>
          <li><code>dependency</code> blocks wire modules together — Terragrunt applies them in order</li>
          <li><code>mock_outputs</code> let you plan before the dependency is applied</li>
          <li><code>terragrunt run-all apply</code> walks the full dependency graph</li>
        </ul>
        <aside class="notes">dependency blocks are how terragrunt expresses relationships between separate terraform state files. in this example, the ecs module declares that it depends on the vpc module. when you run terragrunt run-all apply, terragrunt builds a dependency graph and applies modules in the correct order — vpc first, then ecs. without terragrunt, you would need to use terraform_remote_state data sources and manually ensure the correct apply order, which is fragile and doesn't scale. mock_outputs are critical for ci pipelines: they let you run terraform plan on the ecs module even when the vpc hasn't been applied yet in that environment. the mock values satisfy the variable references during planning so the plan can complete, and mock_outputs_allowed_terraform_commands restricts mocks to only plan and validate — during apply, real outputs are required. in our codebase, we use dependency blocks extensively: api services depend on albs, albs depend on vpcs, database user modules depend on rds clusters.</aside>
      </section>
    </section>

    <!-- SLIDE 8: CI/CD at Tabs -->
    <section>
      <section>
        <h2 class="section-header">how we deploy at tabs</h2>
        <p style="color: var(--green); font-size: 0.6em;">slide.cicd_at_tabs: Creating...</p>
        <aside class="notes">this section covers how terraform and terragrunt are integrated into our github actions ci/cd pipeline at tabs. two sub-slides: the conceptual pr workflow, then a simplified but realistic github actions yaml snippet. this is where the audience sees how all the previous concepts come together in practice — the modules, the terragrunt wrappers, the dependency graphs, all orchestrated by ci.</aside>
      </section>

      <section>
        <h3>plan on pr, apply on merge</h3>
        <ul>
          <li><span class="green">On PR open / push</span> → <code>terragrunt plan</code> runs automatically</li>
          <li>Plan output is visible in the <span class="amber">workflow run logs</span> — reviewers check the Actions tab</li>
          <li>Branch protection requires the plan workflow to pass before merge</li>
          <li><span class="green">On merge to main</span> → <code>terragrunt apply-all</code> runs automatically</li>
          <li>Applies are <span class="amber">gated</span> — only the main branch can trigger applies</li>
          <li>Dev can also be force-deployed on PR with a <code>deploy-dev</code> label</li>
        </ul>
        <br>
        <p style="color: var(--green); font-size: 0.6em; text-align: center;">PR → Plan → Review → Merge → Apply</p>
        <aside class="notes">the fundamental principle: nobody runs terragrunt apply from their laptop. all infrastructure changes go through the same code review process as application code — open a pr, the ci pipeline runs terragrunt plan, reviewers inspect the plan output in the github actions workflow logs, and only after the pr is approved and merged does terragrunt apply execute. branch protection rules enforce this: the plan workflow must pass before a pr can be merged, and applies only trigger on pushes to main. for the dev environment, there's an additional escape hatch: adding a deploy-dev label to a pr triggers an apply without requiring a merge. this is useful when you need to test infrastructure changes in a real environment before committing to them. production applies are more strictly gated — they only run on merge to main, and they only trigger when files in the prod terragrunt directory have changed.</aside>
      </section>

      <section>
        <h3>matrix deploys in github actions</h3>
        <p>Workflows detect which services changed and deploy only those:</p>
        <pre><code class="language-yaml">name: Dev Deploy
on:
  pull_request:
    branches: [main]
    paths: ['apps/**']
  push:
    branches: [main]
    paths: ['apps/**']

jobs:
  detect-changes:
    # Matrix generation — only deploy services that changed
    runs-on: ubuntu-latest
    outputs:
      matrix: $${{ steps.changes.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: changes
        uses: matrix-by-diff  # detects changed services

  deploy:
    needs: detect-changes
    strategy:
      matrix: $${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4

      - name: Terragrunt Plan or Apply
        env:
          TG_ACTION: $${{ github.ref == 'refs/heads/main'
            &amp;&amp; 'apply' || 'plan' }}
        run: |
          cd apps/$${{ matrix.service }}/terragrunt/dev
          terragrunt run-all $$TG_ACTION
            --terragrunt-non-interactive</code></pre>
        <aside class="notes">this yaml is simplified but structurally accurate to what we run. the key architectural decision is matrix-driven deploys: rather than deploying everything on every push, a detect-changes job analyzes the git diff to determine which services had file changes, then generates a matrix of only those services. the deploy job fans out across the matrix, so if only auth-service changed, only auth-service gets planned or applied. each service has its own terragrunt directory structure containing components like alb, waf, api, and dns — terragrunt run-all handles the dependency ordering between them. we have three separate workflow files: _dev.yaml for development deploys (build container + apply infra), _prod.yaml for production (apply infra only, uses the container image already built in dev), and _artifact.yaml for ecr repository management. reusable workflow steps are pulled from a shared cicd-templates repository maintained by the platform team. aws authentication uses oidc — no static credentials stored in github secrets.</aside>
      </section>
    </section>

    <!-- ============================================ -->
    <!-- SLIDE 9: terraform destroy — Closing         -->
    <!-- ============================================ -->
    <section>
      <h2 class="prompt">terragrunt destroy</h2>
      <br>
      <p style="text-align: center;">all resources (slides) will be destroyed.</p>
      <br>
      <p style="text-align: center; color: #666; font-size: 0.6em;">
        this presentation will self-destruct on <code>terragrunt destroy</code>
      </p>
      <aside class="notes">
        wrap up. thank the audience for their time. remind them that the source code for this presentation is a public github repository — they can clone it and run terragrunt apply to generate their own copy. open the floor for questions. if there are no questions, end with a reminder that the slides will be available and that you're happy to chat about any of the topics covered in more detail afterwards.
      </aside>
    </section>

  HTML

  full_html = <<-FULLHTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${var.talk_title}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/reveal.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/theme/black.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/plugin/highlight/monokai.min.css">
  <style>
${local.custom_css}
  </style>
</head>
<body>
  <div class="reveal">
    <div class="slides">
${local.slides}
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/reveal.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/plugin/highlight/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/plugin/notes/notes.min.js"></script>
  <script>
    Reveal.initialize({
      hash: true,
      slideNumber: true,
      transition: 'none',
      width: 1200,
      height: 700,
      margin: 0.1,
      plugins: [RevealHighlight, RevealNotes]
    });
  </script>
</body>
</html>
  FULLHTML
}
