locals {
  custom_css = <<-CSS
    @import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;600&display=swap');

    :root {
      --pink: #ff6eb4;
      --amber: #ffb000;
      --bg: #0a0a0a;
      --fg: #e0e0e0;
      --code-bg: #1a1a2e;
    }

    body, .reveal {
      background-color: var(--bg);
      font-family: 'Fira Code', 'Courier New', monospace;
      text-transform: lowercase;
    }

    .reveal h1, .reveal h2, .reveal h3 {
      color: var(--pink);
      font-family: 'Fira Code', 'Courier New', monospace;
      text-transform: none;
      font-weight: 600;
      letter-spacing: -0.02em;
    }

    .reveal h1 { font-size: 1.8em; }
    .reveal h2 { font-size: 1.4em; }
    .reveal h3 { font-size: 1.1em; }

    .reveal p, .reveal li, .reveal td {
      color: var(--fg);
      text-align: left;
      font-size: 0.7em;
      line-height: 1.6;
    }

    .reveal ul, .reveal ol {
      display: block;
      margin-left: 1em;
    }

    .reveal .amber { color: var(--amber); }
    .reveal .pink { color: var(--pink); }
    .reveal .dim { color: #666; }

    .reveal pre {
      width: 95%;
      margin: 0.5em auto;
    }

    .reveal pre code {
      font-size: 0.55em;
      line-height: 1.5;
      background: var(--code-bg);
      border: 1px solid var(--pink);
      border-radius: 4px;
      padding: 0.8em;
      max-height: 500px;
      text-transform: none;
    }

    .reveal code:not(pre code) {
      color: var(--amber);
      font-size: 0.9em;
      background: rgba(255, 176, 0, 0.1);
      padding: 0.1em 0.3em;
      border-radius: 3px;
      text-transform: none;
    }

    .reveal .slide-number {
      color: var(--pink);
      font-family: 'Fira Code', monospace;
      font-size: 0.5em;
    }

    .tf-plan {
      font-family: 'Fira Code', monospace;
      text-align: left;
      font-size: 0.65em;
      line-height: 1.8;
    }

    .tf-plan .resource { color: var(--pink); }
    .tf-plan .comment { color: #666; }

    .reveal .prompt::before {
      content: '$ ';
      color: var(--amber);
    }

    .reveal blockquote {
      border-left: 4px solid var(--amber);
      background: rgba(255, 176, 0, 0.05);
      padding: 0.5em 1em;
      width: 85%;
    }

    .reveal table {
      margin: 0.5em auto;
      border-collapse: collapse;
    }

    .reveal table th {
      color: var(--pink);
      border-bottom: 2px solid var(--pink);
      padding: 0.4em 0.8em;
      font-size: 0.65em;
    }

    .reveal table td {
      border-bottom: 1px solid #333;
      padding: 0.4em 0.8em;
      font-size: 0.6em;
    }

    .reveal .section-header {
      border-bottom: 2px solid var(--pink);
      padding-bottom: 0.3em;
      margin-bottom: 0.5em;
    }
  CSS

  slides = <<-HTML

    <!-- ============================================ -->
    <!-- SLIDE 1: terraform init — Title              -->
    <!-- ============================================ -->
    <section>
      <p style="color: var(--amber); font-size: 0.7em; margin-bottom: 0;">$ terraform init</p>
      <p style="color: #666; font-size: 0.55em;">Initializing provider plugins...</p>
      <p style="color: var(--pink); font-size: 0.55em;">Terraform has been successfully initialized!</p>
      <br>
      <h1>${var.talk_title}</h1>
      <p style="color: var(--pink); font-size: 0.8em; text-align: center;">${var.presenter_name}</p>
      <aside class="notes">
        So yes — this deck was generated by running terragrunt apply. Every slide is a resource attribute in HCL.
        If there's a typo, file a PR. Anyway, let's get into it.
      </aside>
    </section>

    <!-- ============================================ -->
    <!-- SLIDE 2: terraform plan — Table of Contents  -->
    <!-- ============================================ -->
    <section>
      <h2 class="prompt">terraform plan</h2>
      <div class="tf-plan">
        <p class="comment"># Terraform will perform the following actions:</p>
        <br>
        <p class="resource">+ slide.history_of_terraform</p>
        <p class="resource">+ slide.why_terraform</p>
        <p class="resource">+ slide.core_concepts</p>
        <p class="resource">+ slide.writing_terraform</p>
        <p class="resource">+ slide.terragrunt</p>
        <p class="resource">+ slide.cicd_at_tabs</p>
        <br>
        <p>Plan: <span class="amber">8 slides</span> to add, <span class="amber">0</span> to change, <span class="amber">0</span> to destroy.</p>
      </div>
      <aside class="notes">
        Here's the agenda, styled as plan output because why not. Six sections, roughly tracking the Terraform lifecycle.
      </aside>
    </section>

    <!-- ============================================ -->
    <!-- terraform apply — Main Content Begins        -->
    <!-- ============================================ -->

    <!-- SLIDE 3: History of Terraform -->
    <section>
      <section>
        <h2 class="section-header">History of Terraform</h2>
        <p style="color: var(--pink); font-size: 0.6em;">slide.history_of_terraform: Creating...</p>
        <aside class="notes">Quick history. Useful context for understanding some of the design decisions and the recent license drama.</aside>
      </section>

      <section>
        <h3>HashiCorp</h3>
        <ul>
          <li><span class="amber">2012</span> — Mitchell Hashimoto and Armon Dadgar start HashiCorp</li>
          <li>Vagrant was the first product — codifying dev environments</li>
          <li>Then Consul, Vault, Nomad, Packer — all infrastructure tooling</li>
        </ul>
        <aside class="notes">Mitchell was already well-known for Vagrant. The thesis: if you can codify dev environments, you can codify production infra too.</aside>
      </section>

      <section>
        <h3>Terraform Launches</h3>
        <ul>
          <li><span class="amber">July 2014</span> — Terraform 0.1, open source under MPL 2.0</li>
          <li>Big idea: one tool that works across cloud providers</li>
          <li>Plan → apply workflow was there from the start</li>
          <li><span class="amber">HCL</span> replaced JSON configs — human-readable but still machine-parseable</li>
        </ul>
        <aside class="notes">CloudFormation existed but was AWS-only. Terraform bet on multi-cloud. HCL was important — JSON is painful to write by hand, YAML has its own foot-guns, HCL tried to split the difference.</aside>
      </section>

      <section>
        <h3>The License Change</h3>
        <ul>
          <li><span class="amber">August 2023</span> — HashiCorp relicenses Terraform from MPL 2.0 to BSL 1.1</li>
          <li>BSL restricts competing commercial use — most production use is fine</li>
          <li><span class="amber">September 2023</span> — Linux Foundation announces <span class="pink">OpenTofu</span>, a community fork keeping MPL 2.0</li>
          <li>For us, nothing changed — BSL doesn't affect how we use it</li>
        </ul>
        <aside class="notes">Controversial but the practical impact is minimal for most teams. OpenTofu exists as an insurance policy if you're worried about the direction. We stayed on Terraform — the license doesn't restrict our use case.</aside>
      </section>
    </section>

    <!-- SLIDE 4: Why Terraform -->
    <section>
      <section>
        <h2 class="section-header">Why Terraform?</h2>
        <p style="color: var(--pink); font-size: 0.6em;">slide.why_terraform: Creating...</p>
        <aside class="notes">There are alternatives. Why did we (and most of the industry) end up on Terraform?</aside>
      </section>

      <section>
        <h3>IaC Principles (the quick version)</h3>
        <ul>
          <li><span class="amber">Declarative</span> — you describe what you want, not how to get there</li>
          <li><span class="amber">Idempotent</span> — run it twice, same result</li>
          <li><span class="amber">Version-controlled</span> — infra changes go through PRs like any other code</li>
          <li>Your .tf files <em>are</em> the docs for what's deployed</li>
        </ul>
        <aside class="notes">These apply to all IaC tools. Terraform's plan/apply workflow makes the declarative model really tangible — you always see what's going to change before it changes.</aside>
      </section>

      <section>
        <h3>Terraform vs. the Alternatives</h3>
        <table>
          <thead>
            <tr>
              <th></th>
              <th>Terraform</th>
              <th>CloudFormation</th>
              <th>Pulumi</th>
              <th>CDK</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="amber">Language</td>
              <td>HCL</td>
              <td>JSON / YAML</td>
              <td>Python, TS, Go…</td>
              <td>Python, TS, Go…</td>
            </tr>
            <tr>
              <td class="amber">Multi-cloud</td>
              <td class="pink">Yes (native)</td>
              <td>AWS only</td>
              <td class="pink">Yes</td>
              <td>AWS only</td>
            </tr>
            <tr>
              <td class="amber">Model</td>
              <td>Declarative</td>
              <td>Declarative</td>
              <td>Imperative</td>
              <td>Imperative → CFN</td>
            </tr>
            <tr>
              <td class="amber">Providers</td>
              <td class="pink">3,000+</td>
              <td>~200 AWS types</td>
              <td>~150</td>
              <td>AWS constructs</td>
            </tr>
            <tr>
              <td class="amber">State</td>
              <td>Explicit (S3, etc.)</td>
              <td>Managed by AWS</td>
              <td>Explicit / managed</td>
              <td>CloudFormation</td>
            </tr>
          </tbody>
        </table>
        <aside class="notes">CFN is solid if you're all-in on AWS, but you're locked in. Pulumi lets you use real languages which is appealing, but the declarative model is a feature not a bug — fewer ways to shoot yourself in the foot. CDK compiles down to CloudFormation so you inherit all its limits. The provider ecosystem is Terraform's real moat.</aside>
      </section>

      <section>
        <h3>What actually sold us</h3>
        <ul>
          <li><span class="pink">3,000+ providers</span> — if it has an API, there's probably a Terraform provider</li>
          <li><span class="pink">Plan/apply</span> — you always see what's going to change before it happens</li>
          <li><span class="pink">State</span> — Terraform tracks the mapping between your config and real resources</li>
          <li><span class="pink">Hiring</span> — HCL is the lingua franca of infra. Try hiring for Pulumi expertise.</li>
        </ul>
        <aside class="notes">The hiring point is underrated. Most infra engineers already know Terraform. The community and module registry are massive. Pulumi is technically interesting but the talent pool is much smaller.</aside>
      </section>
    </section>

    <!-- SLIDE 5: Core Concepts -->
    <section>
      <section>
        <h2 class="section-header">Core Concepts</h2>
        <p style="color: var(--pink); font-size: 0.6em;">slide.core_concepts: Creating...</p>
        <aside class="notes">Refresher on the building blocks. Won't belabor the basics — mostly here so we have a shared vocabulary for the Terragrunt section.</aside>
      </section>

      <section>
        <h3>Providers</h3>
        <p>Plugins that let Terraform talk to APIs.</p>
        <pre><code class="language-hcl">provider "aws" {
  region = "us-east-1"
}

provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}</code></pre>
        <ul>
          <li>Separate binaries, pulled in during <code>terraform init</code></li>
          <li>Version-pinned in <code>required_providers</code></li>
          <li>You can mix providers — AWS for infra, Datadog for monitoring, same config</li>
        </ul>
        <aside class="notes">The AWS provider alone has hundreds of resource types. We also use providers for Datadog, GitHub, etc.</aside>
      </section>

      <section>
        <h3>Resources</h3>
        <p>Each resource maps to a real thing in your cloud account.</p>
        <pre><code class="language-hcl">resource "aws_s3_bucket" "logs" {
  bucket = "my-app-logs-bucket"

  tags = {
    Environment = "production"
  }
}</code></pre>
        <ul>
          <li><code>resource "TYPE" "NAME" { ... }</code> — type prefix tells you the provider</li>
          <li>Tracked in state by address: <code>aws_s3_bucket.logs</code></li>
        </ul>
        <aside class="notes">If you rename a resource, Terraform thinks the old one should be destroyed and a new one created. The name is local to your config — the actual cloud object has its own identity.</aside>
      </section>

      <section>
        <h3>Variables &amp; Outputs</h3>
        <pre><code class="language-hcl">variable "environment" {
  type        = string
  description = "Deployment environment"
  default     = "dev"
}

output "bucket_arn" {
  description = "ARN of the logs bucket"
  value       = aws_s3_bucket.logs.arn
}</code></pre>
        <ul>
          <li><span class="amber">Variables</span> — inputs. Set via <code>-var</code>, <code>.tfvars</code> files, or env vars</li>
          <li><span class="amber">Outputs</span> — values exported after apply, used by other modules or CI</li>
          <li><span class="amber">Locals</span> — internal computed values (think private variables)</li>
        </ul>
        <aside class="notes">Think of it as a function signature: variables are params, outputs are return values, locals are internal vars. This matters a lot when you start composing modules.</aside>
      </section>

      <section>
        <h3>State</h3>
        <ul>
          <li>Terraform keeps a <span class="amber">state file</span> mapping your config to real resources</li>
          <li>Locally it's just <code>terraform.tfstate</code> — for teams, use a remote backend (S3 + DynamoDB)</li>
          <li>Contains sensitive data. Treat it like a secret.</li>
          <li>Locking prevents two people from applying at the same time</li>
        </ul>
        <pre><code class="language-hcl">terraform {
  backend "s3" {
    bucket         = "my-terraform-state"
    key            = "prod/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}</code></pre>
        <aside class="notes">Lose the state file and you have to import everything by hand. Remote state with locking is non-negotiable for teams. We use S3 + DynamoDB — Terragrunt manages the backend config for us, more on that later.</aside>
      </section>

      <section>
        <h3>Modules</h3>
        <ul>
          <li>Just a directory of <code>.tf</code> files — that's it</li>
          <li>Called with a <code>module</code> block, passing variables as arguments</li>
        </ul>
        <pre><code class="language-hcl">module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.1.0"

  name = "my-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-east-1a", "us-east-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]
}</code></pre>
        <ul>
          <li>Public registry has thousands (VPC, ECS, RDS, etc.)</li>
          <li>We also write internal modules that bake in our conventions</li>
        </ul>
        <aside class="notes">Your internal modules encode your company's opinions — tagging standards, security defaults, naming conventions. We have a terraform-modules repo with a tiered structure: core, component, service.</aside>
      </section>
    </section>

    <!-- SLIDE 6: Writing Terraform -->
    <section>
      <section>
        <h2 class="section-header">Writing Terraform</h2>
        <p style="color: var(--pink); font-size: 0.6em;">slide.writing_terraform: Creating...</p>
        <aside class="notes">Enough theory. Here's what real Terraform looks like.</aside>
      </section>

      <section>
        <h3>A Practical Example: EC2 Instance</h3>
        <pre><code class="language-hcl">locals {
  environment = "production"
  app_name    = "api-server"

  common_tags = {
    ManagedBy   = "terraform"
    Environment = local.environment
    Application = local.app_name
  }
}

variable "instance_type" {
  type        = string
  default     = "t3.micro"
  description = "EC2 instance type"
}

variable "ami_id" {
  type        = string
  description = "AMI ID for the instance"
}</code></pre>
        <aside class="notes">Locals for shared/computed values, variables for things that change per environment. The common_tags pattern is everywhere — makes sure every resource gets tagged consistently.</aside>
      </section>

      <section>
        <h3>The Resource &amp; Output</h3>
        <pre><code class="language-hcl">resource "aws_instance" "app" {
  ami           = var.ami_id
  instance_type = var.instance_type
  subnet_id     = module.vpc.private_subnets[0]

  tags = merge(local.common_tags, {
    Name = "$${local.app_name}-$${local.environment}"
  })

  lifecycle {
    create_before_destroy = true
  }
}

output "instance_id" {
  description = "ID of the EC2 instance"
  value       = aws_instance.app.id
}

output "private_ip" {
  description = "Private IP address"
  value       = aws_instance.app.private_ip
}</code></pre>
        <aside class="notes">Notice the VPC module output reference for the subnet — that's how modules compose. merge() combines common tags with resource-specific ones. create_before_destroy is a common pattern for zero-downtime updates.</aside>
      </section>
    </section>

    <!-- SLIDE 7: Terragrunt -->
    <section>
      <section>
        <h2 class="section-header">Terragrunt</h2>
        <p style="color: var(--pink); font-size: 0.6em;">slide.terragrunt: Creating...</p>
        <aside class="notes">Thin wrapper around Terraform by Gruntwork. If you haven't used it, no worries. This deck is actually managed by Terragrunt — the module's in modules/presentation/ and the live config passes inputs via terragrunt.hcl.</aside>
      </section>

      <section>
        <h3>The Problem</h3>
        <ul>
          <li>Vanilla Terraform gets <span class="amber">repetitive</span> fast</li>
          <li>Same backend config, same provider block, copy-pasted across dozens of directories</li>
          <li>No built-in way to express <span class="amber">dependencies between stacks</span></li>
          <li>Environment promotion means duplicating configs by hand</li>
        </ul>
        <p style="color: var(--pink); font-size: 0.65em;">Terragrunt's whole thing: keep your Terraform DRY.</p>
        <aside class="notes">5 services × 2 environments = 10 nearly-identical backend configs. It gets old. Terragrunt eliminates most of that.</aside>
      </section>

      <section>
        <h3>DRY Root Modules</h3>
        <p>One root config, thin overrides everywhere else.</p>
        <pre><code class="language-hcl"># root terragrunt.hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket         = "my-company-terraform-state"
    key            = "$${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-locks"
  }
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = &lt;&lt;EOF
provider "aws" {
  region = "us-east-1"
}
EOF
}</code></pre>
        <aside class="notes">Every child module inherits this. path_relative_to_include() namespaces state files by directory automatically. The generate blocks write backend.tf and provider.tf before Terraform runs — Terraform never sees Terragrunt, just normal .tf files.</aside>
      </section>

      <section>
        <h3>Environment Promotion</h3>
        <pre><code class="language-bash">sre/
├── terragrunt.hcl              # root config
├── dev/
│   ├── account.terragrunt.hcl  # AWS account ID + profile
│   └── us-east-1/
│       ├── region.terragrunt.hcl
│       └── dev/
│           ├── environment.terragrunt.hcl
│           ├── vpc/terragrunt.hcl
│           ├── ecs/terragrunt.hcl
│           └── rds-backend-cluster/terragrunt.hcl
└── prod/
    ├── account.terragrunt.hcl  # different AWS account
    └── us-east-1/
        └── prod/
            ├── vpc/terragrunt.hcl
            ├── ecs/terragrunt.hcl
            └── rds-backend-cluster/terragrunt.hcl</code></pre>
        <p>Each leaf <code>terragrunt.hcl</code> is minimal:</p>
        <pre><code class="language-hcl">include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../modules//vpc"
}

inputs = {
  environment = "dev"
  cidr_block  = "10.0.0.0/16"
}</code></pre>
        <aside class="notes">The directory structure IS the environment model. Account, region, environment, component — each layer has its own .hcl that sets context. Dev and prod are in separate AWS accounts. Promoting to prod = same module source, different inputs, different account.</aside>
      </section>

      <section>
        <h3>Remote State Management</h3>
        <ul>
          <li>Terragrunt <span class="pink">generates</span> the S3 backend config from the <code>remote_state</code> block</li>
          <li>State key = directory path, automatically</li>
          <li>Creates the S3 bucket and DynamoDB table if they don't exist yet</li>
          <li>No more copy-pasting backend blocks</li>
        </ul>
        <pre><code class="language-bash"># Without Terragrunt: manual backend in every module
# With Terragrunt: one remote_state block in root, inherited everywhere

# State paths generated automatically:
# dev/vpc/     → s3://bucket/dev/vpc/terraform.tfstate
# prod/ecs/    → s3://bucket/prod/ecs/terraform.tfstate</code></pre>
        <aside class="notes">Huge quality-of-life win. Backend config in vanilla Terraform can't use variables — it's one of the most annoying limitations. Terragrunt sidesteps it by generating the file before Terraform runs.</aside>
      </section>

      <section>
        <h3>Dependency Graphs</h3>
        <pre><code class="language-hcl"># ecs/terragrunt.hcl
dependency "vpc" {
  config_path = "../vpc"

  mock_outputs = {
    vpc_id             = "vpc-mock-12345"
    private_subnet_ids = ["subnet-mock-1", "subnet-mock-2"]
  }
  mock_outputs_allowed_terraform_commands = ["plan", "validate"]
}

inputs = {
  vpc_id     = dependency.vpc.outputs.vpc_id
  subnet_ids = dependency.vpc.outputs.private_subnet_ids
}</code></pre>
        <ul>
          <li><code>dependency</code> blocks wire modules together — Terragrunt applies them in order</li>
          <li><code>mock_outputs</code> let you plan before the dependency is applied</li>
          <li><code>terragrunt run-all apply</code> walks the full dependency graph</li>
        </ul>
        <aside class="notes">Without this, cross-stack references need remote state data sources and manual ordering. mock_outputs matter for CI — you need to plan the ECS module even when the VPC doesn't exist in that environment yet.</aside>
      </section>
    </section>

    <!-- SLIDE 8: CI/CD at Tabs -->
    <section>
      <section>
        <h2 class="section-header">CI/CD at Tabs</h2>
        <p style="color: var(--pink); font-size: 0.6em;">slide.cicd_at_tabs: Creating...</p>
        <aside class="notes">How this all fits into our actual deploy pipeline.</aside>
      </section>

      <section>
        <h3>The PR Workflow</h3>
        <ul>
          <li><span class="pink">On PR open / push</span> → <code>terragrunt plan</code> runs automatically</li>
          <li>Plan output is visible in the <span class="amber">workflow run logs</span> — reviewers check the Actions tab</li>
          <li>Branch protection requires the plan workflow to pass before merge</li>
          <li><span class="pink">On merge to main</span> → <code>terragrunt apply-all</code> runs automatically</li>
          <li>Applies are <span class="amber">gated</span> — only the main branch can trigger applies</li>
          <li>Dev can also be force-deployed on PR with a <code>deploy-dev</code> label</li>
        </ul>
        <br>
        <p style="color: var(--pink); font-size: 0.6em; text-align: center;">PR → Plan → Review → Merge → Apply</p>
        <aside class="notes">Nobody runs terragrunt apply from their laptop. Everything goes through CI. The deploy-dev label is an escape hatch for when you need to test infra changes before merging.</aside>
      </section>

      <section>
        <h3>GitHub Actions: Matrix-Driven Deploys</h3>
        <p>Workflows detect which services changed and deploy only those:</p>
        <pre><code class="language-yaml">name: Dev Deploy
on:
  pull_request:
    branches: [main]
    paths: ['apps/**']
  push:
    branches: [main]
    paths: ['apps/**']

jobs:
  detect-changes:
    # Matrix generation — only deploy services that changed
    runs-on: ubuntu-latest
    outputs:
      matrix: $${{ steps.changes.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: changes
        uses: matrix-by-diff  # detects changed services

  deploy:
    needs: detect-changes
    strategy:
      matrix: $${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4

      - name: Terragrunt Plan or Apply
        env:
          TG_ACTION: $${{ github.ref == 'refs/heads/main'
            &amp;&amp; 'apply' || 'plan' }}
        run: |
          cd apps/$${{ matrix.service }}/terragrunt/dev
          terragrunt run-all $$TG_ACTION
            --terragrunt-non-interactive</code></pre>
        <aside class="notes">Simplified but close to what we actually run. matrix-by-diff figures out which services changed, then we only deploy those. Each service has its own terragrunt dir with ALB, WAF, API, DNS components. Separate workflows for dev vs prod vs artifact (ECR). We pull shared steps from a cicd-templates repo.</aside>
      </section>
    </section>

    <!-- ============================================ -->
    <!-- SLIDE 9: terraform destroy — Closing         -->
    <!-- ============================================ -->
    <section>
      <h2 class="prompt">terragrunt destroy</h2>
      <br>
      <p style="text-align: center;">All resources (slides) will be destroyed.</p>
      <br>
      <p style="text-align: center; color: var(--amber); font-size: 1em;">Questions?</p>
      <br>
      <p style="text-align: center; color: #666; font-size: 0.6em;">
        This presentation will self-destruct on <code>terragrunt destroy</code>
      </p>
      <aside class="notes">
        That's it. Source code for this deck is on GitHub — clone it, terragrunt apply, you've got your own copy. Thanks everyone.
      </aside>
    </section>

  HTML

  full_html = <<-FULLHTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${var.talk_title}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/reveal.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/theme/black.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/plugin/highlight/monokai.min.css">
  <style>
${local.custom_css}
  </style>
</head>
<body>
  <div class="reveal">
    <div class="slides">
${local.slides}
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/reveal.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/plugin/highlight/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.2.1/plugin/notes/notes.min.js"></script>
  <script>
    Reveal.initialize({
      hash: true,
      slideNumber: true,
      transition: 'none',
      width: 1200,
      height: 700,
      margin: 0.1,
      plugins: [RevealHighlight, RevealNotes]
    });
  </script>
</body>
</html>
  FULLHTML
}
